
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class AdminPortel extends javax.swing.JFrame {

    /**
     * Creates new form Admin_2
     */
    public AdminPortel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ckbox = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(153, 213,239,200));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 129, 193), 3));
        jPanel3.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255,255, 255,100));
        jPanel2.setLayout(null);
        jPanel3.add(jPanel2);
        jPanel2.setBounds(26, 214, 0, 0);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255, 110));
        jPanel4.setLayout(null);
        jPanel3.add(jPanel4);
        jPanel4.setBounds(563, 45, 0, 0);

        user.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel3.add(user);
        user.setBounds(300, 90, 370, 50);
        jPanel3.add(jLabel3);
        jLabel3.setBounds(33, 81, 0, 0);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/password-76-48.png"))); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(60, 170, 50, 60);

        jButton3.setBackground(new java.awt.Color(0,153,204));
        jButton3.setFont(new java.awt.Font("Ajith  New  S", 1, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(400, 330, 130, 50);

        pass.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jPanel3.add(pass);
        pass.setBounds(300, 180, 370, 50);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel5.setText("Password :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(110, 180, 130, 50);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel7.setText("User ID :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(130, 90, 110, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/user.png"))); // NOI18N
        jPanel3.add(jLabel8);
        jLabel8.setBounds(60, 90, 60, 50);

        ckbox.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        ckbox.setText("Show Password");
        ckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckboxActionPerformed(evt);
            }
        });
        jPanel3.add(ckbox);
        ckbox.setBounds(300, 270, 130, 21);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(350, 310, 760, 420);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/circled-left-2.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(40, 710, 70, 50);

        jPanel5.setBackground(new java.awt.Color(0,153,204,220));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 130, 170), 2));
        jPanel5.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Castellar", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText(" Patient Record Management System");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(210, -30, 1000, 190);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 30, 1450, 130);

        jPanel6.setBackground(new java.awt.Color(255,255,255,200));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 88, 132)));
        jPanel6.setForeground(new java.awt.Color(0, 153, 204));
        jPanel6.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Goudy Old Style", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 88, 132));
        jLabel6.setText("Welcome To The Admin Portal");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(80, 10, 400, 60);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(450, 220, 550, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/doctor-n1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1450, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        A_HomePage hp = new A_HomePage();
        hp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          
         if(user.getText().trim().isEmpty() && pass.getText().trim().isEmpty()){
              user.setText("Username is Empty");
              pass.setText("Password is Empty");
              
          }
          if(user.getText().trim().isEmpty()){
              user.setText("Username is Empty");
          }else if(pass.getText().trim().isEmpty())
          {
              pass.setText("Password is Empty");
          }
          else{
              
        try{
             
             
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/trojan_squad","root","");
             String sql = "Select * from admin where id=? and password=?";
             PreparedStatement pst =con.prepareStatement(sql);
             pst.setString(1,user.getText());
             pst.setString(2,pass.getText());
             ResultSet rs =pst.executeQuery();
             
             if(rs.next())
             {
                 JOptionPane.showMessageDialog(null,"Username and Password Matched");
                  AdminPanel ap = new  AdminPanel();
                 ap.setVisible(true);
                 setVisible(false);
                 
             }else{
                 JOptionPane.showMessageDialog(null,"Username and Password Donot Matched");
                 user.setText("");
                 pass.setText("");
             }
             
             con.close();
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
         }
       }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    //Show password option
    private void ckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckboxActionPerformed
        // TODO add your handling code here:
        if(ckbox.isSelected()){
        pass.setEchoChar((char)0);
    }
        else{
            pass.setEchoChar('*');
        }
    }//GEN-LAST:event_ckboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPortel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPortel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPortel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPortel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPortel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ckbox;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
