
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class DocRegForm extends javax.swing.JFrame {

    /**
     * Creates new form DocRegForm
     */
    public DocRegForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        depart = new javax.swing.JTextField();
        job = new javax.swing.JTextField();
        special = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ckbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1410, 700));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0,153,204,240));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 105, 137), 2));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Castellar", 1, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Doctor Registration");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(230, 20, 500, 100);
        jPanel3.add(jLabel1);
        jLabel1.setBounds(1010, 30, 0, 70);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(260, 60, 950, 130);

        add.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add);
        add.setBounds(310, 510, 250, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0,153,204));
        jLabel6.setText("Doctor ID:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(150, 340, 120, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0,153,204));
        jLabel7.setText("Name:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(190, 430, 80, 40);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0,153,204));
        jLabel10.setText("Addres :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(180, 520, 100, 40);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0,153,204));
        jLabel14.setText("Department :");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(640, 340, 130, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0,153,204));
        jLabel5.setText("Speciality :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(660, 430, 110, 40);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0,153,204));
        jLabel11.setText("Designation :");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(640, 510, 130, 40);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0,153,204));
        jLabel12.setText("Contact No :");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(140, 590, 130, 40);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0,153,204));
        jLabel13.setText("Email :");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(200, 670, 70, 40);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0,153,204));
        jLabel15.setText("Password :");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(670, 600, 100, 40);

        email.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email);
        email.setBounds(310, 670, 250, 40);

        fname.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        jPanel2.add(fname);
        fname.setBounds(310, 430, 250, 40);

        id.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel2.add(id);
        id.setBounds(310, 340, 250, 40);

        depart.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        depart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departActionPerformed(evt);
            }
        });
        jPanel2.add(depart);
        depart.setBounds(820, 340, 250, 40);

        job.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        job.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobActionPerformed(evt);
            }
        });
        jPanel2.add(job);
        job.setBounds(820, 500, 250, 40);

        special.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        special.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialActionPerformed(evt);
            }
        });
        jPanel2.add(special);
        special.setBounds(820, 420, 250, 40);

        number.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });
        jPanel2.add(number);
        number.setBounds(310, 600, 250, 40);

        pass.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel2.add(pass);
        pass.setBounds(820, 590, 250, 40);

        jButton1.setBackground(new java.awt.Color(0,153,204,240));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(840, 720, 130, 50);

        jButton2.setBackground(new java.awt.Color(0,153,204,240));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(1000, 720, 140, 50);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/circled-left-2.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(30, 730, 60, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/adminpanel_doctor.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(100, 40, 140, 160);

        ckbox.setText("Show password");
        ckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckboxActionPerformed(evt);
            }
        });
        jPanel2.add(ckbox);
        ckbox.setBounds(1070, 600, 110, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void departActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departActionPerformed

    private void jobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobActionPerformed

    private void specialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialActionPerformed

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        id.setText("");
        fname.setText("");
        add.setText("");
        number.setText("");
        email.setText("");
        depart.setText("");
        special.setText("");
        job.setText("");
        pass.setText(""); 
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /* private String generateRandomUserID(String user_id) {
    // Generate a random alphanumeric ID of length 8
    String characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    StringBuilder randomID = new StringBuilder();
    for (int i = 0; i < 8; i++) {
        int index = (int) (Math.random() * characters.length());
        randomID.append(characters.charAt(index));
    }
    return randomID.toString();
}*/
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         
        String user_id = id.getText();
       // String randomUserID = generateRandomUserID(user_id);
       
       if(user_id.isEmpty()){
           JOptionPane.showMessageDialog(rootPane,"User ID cannot be empty" );
       }
        
        String f_name =fname.getText();
       
        String address =add.getText();
        String department =depart.getText();
        String designation =job.getText();
        String speciality =special.getText();
        String contact =number.getText();
        String Email =email.getText();
        
          //Email validation
        String emailValidationMessage = validateEmail(Email);
        if (emailValidationMessage != null) {
        JOptionPane.showMessageDialog(rootPane, emailValidationMessage, "Validation Error", JOptionPane.ERROR_MESSAGE);
        
    }
        
        String password =String.valueOf(pass.getPassword());
        
        String passwordValidationMessage = isPassword(password);
        if (passwordValidationMessage != null) {
        // Display the password validation error message
        JOptionPane.showMessageDialog(rootPane, passwordValidationMessage, "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
        
        // Validate the password
         
      if (!isPasswordLengthValid(password)) {
        JOptionPane.showMessageDialog(rootPane, "Password must be at least 8 characters long.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!containsUppercaseLetter(password)) {
        JOptionPane.showMessageDialog(rootPane, "Password must contain at least one uppercase letter.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!containsLowercaseLetter(password)) {
        JOptionPane.showMessageDialog(rootPane, "Password must contain at least one lowercase letter.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!containsSpecialCharacter(password)) {
        JOptionPane.showMessageDialog(rootPane, "Password must contain at least one special character.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }


        try 
        {
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/trojan_squad","root","");
           String q = "INSERT INTO  doctor(doctor_id,user_name,address,contact_no,email,department,speciality,designation,password) values ('"+user_id+"','"+f_name+"','"+address+"','"+contact+"','"+Email+"','"+department+"','"+speciality+"','"+designation+"','"+password+"')";
           
           PreparedStatement pst =null;
          
           pst =con.prepareStatement(q); 
         
           
          
          
           pst.execute(q);
           
              JOptionPane.showMessageDialog(rootPane,"Registered Successfully");
         
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Registration Failed!",
               "Swing Tester", JOptionPane.ERROR_MESSAGE);
            
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private String isPassword(String password) {
    if (password.isEmpty()) {
        //JOptionPane.showMessageDialog(rootPane, "Password cannot be empty", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return "Password cannot be empty";
    }
    return null; // Password is not empty
}

    
     private String validateEmail(String email) {
    // Use a regular expression to validate the email address format
    String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
    
    if (email.isEmpty()) {
        return "Email address cannot be empty.";
    }
    
    if (!email.matches(emailRegex)) {
        return "Invalid email address format.";
    }

   

    return null; // Email is valid
}
 
  
  
     
     
 private boolean isPasswordLengthValid(String password) {
    return password.length() >= 8;
}

private boolean containsUppercaseLetter(String password) {
    for (char c : password.toCharArray()) {
        if (Character.isUpperCase(c)) {
            return true;
        }
    }
    return false;
}

private boolean containsLowercaseLetter(String password) {
    for (char c : password.toCharArray()) {
        if (Character.isLowerCase(c)) {
            return true;
        }
    }
    return false;
}

private boolean containsSpecialCharacter(String password) {
    String specialCharacters = "!@#$%^&*()-_=+[]{}|;:'\",.<>/?";
    for (char c : password.toCharArray()) {
        if (specialCharacters.contains(String.valueOf(c))) {
            return true;
        }
    }
    return false;
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        AdminPanel ap = new AdminPanel();
        ap.setVisible(true);
        this.dispose();
         
    }//GEN-LAST:event_jButton3MouseClicked

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void ckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckboxActionPerformed
        // TODO add your handling code here:
        if(ckbox.isSelected()){
        pass.setEchoChar((char)0);
    }
        else{
            pass.setEchoChar('*');
        }
    }//GEN-LAST:event_ckboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DocRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DocRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DocRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DocRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DocRegForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JCheckBox ckbox;
    private javax.swing.JTextField depart;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField job;
    private javax.swing.JTextField number;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField special;
    // End of variables declaration//GEN-END:variables
}
