
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class StaffProtal extends javax.swing.JFrame {
     
    
    String id=" ";
    /**
     * Creates new form T_StaffProtal
     */
    public StaffProtal() {
        initComponents();
        
       
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ckbox = new javax.swing.JCheckBox();
        rpw = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0,153,204,220));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 130, 170), 2));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Castellar", 1, 40)); // NOI18N
        jLabel2.setText(" Patient Record Management System");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(240, -30, 1000, 190);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1450, 130));

        jPanel3.setBackground(new java.awt.Color(255,255,255,200));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 86, 130)));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Goudy Old Style", 1, 33)); // NOI18N
        jLabel3.setText("Welcome To The Staff Portal");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(80, 10, 390, 60);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 550, 70));

        jPanel4.setBackground(new java.awt.Color(153, 213,239,200));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 130, 191), 3));
        jPanel4.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/user.png"))); // NOI18N
        jPanel4.add(jLabel4);
        jLabel4.setBounds(33, 81, 60, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/password-76-48.png"))); // NOI18N
        jPanel4.add(jLabel5);
        jLabel5.setBounds(40, 190, 50, 60);

        user.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jPanel4.add(user);
        user.setBounds(280, 90, 370, 50);

        pass.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jPanel4.add(pass);
        pass.setBounds(280, 190, 370, 50);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel6.setText("Password :");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(100, 200, 130, 50);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel7.setText("User ID :");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(120, 80, 110, 50);

        jButton1.setBackground(new java.awt.Color(0,153,204,220));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(380, 340, 140, 40);

        ckbox.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        ckbox.setText("Show Password");
        ckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckboxActionPerformed(evt);
            }
        });
        jPanel4.add(ckbox);
        ckbox.setBounds(280, 280, 130, 21);

        rpw.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rpw.setText("Reset Password");
        rpw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpwActionPerformed(evt);
            }
        });
        jPanel4.add(rpw);
        rpw.setBounds(500, 280, 120, 23);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 760, 420));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/circled-left-2.png"))); // NOI18N
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 730, 60, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Medical-Group12 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        HomePage hp = new HomePage();
        hp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         if(user.getText().trim().isEmpty() && pass.getText().trim().isEmpty()){
              user.setText("Username is Empty");
              pass.setText("Password is Empty");
              
          }
          if(user.getText().trim().isEmpty()){
              user.setText("Username is Empty");
          }else if(pass.getText().trim().isEmpty())
          {
              pass.setText("Password is Empty");
          }
          else{
              
          
        
         try{
             
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/trojan_squad","root","");
             String sql = "Select * from staff where staff_id=?";
             PreparedStatement pst =con.prepareStatement(sql);
             pst.setString(1,user.getText());
            // pst.setString(2,pass.getText());
             ResultSet rs =pst.executeQuery();
             
             if(rs.next())
             {
                String storedPassword =rs.getString("password");
                 if(storedPassword.equals(pass.getText()))
                 {
                 JOptionPane.showMessageDialog(null,"Username and Password Matched");
                 
                  String msg = user.getText();
                
                 
                 new StaffPanel(msg).setVisible(true);
                 setVisible(false);
                 }
                 else
                 {
                      JOptionPane.showMessageDialog(null,"Password Entered is Wrong");
                    // user.setText("");
                      pass.setText("");
                 }
                 
             }else{
                JOptionPane.showMessageDialog(null,"Username does not exist");
                 user.setText("");
                 pass.setText("");
             }
             
             con.close();
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
         }
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckboxActionPerformed
        // TODO add your handling code here:
        if(ckbox.isSelected()){
            pass.setEchoChar((char)0);
        }
        else{
            pass.setEchoChar('*');
        }
    }//GEN-LAST:event_ckboxActionPerformed

    private void rpwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpwActionPerformed
        // TODO add your handling code here:

        ResetPwStaff pp = new ResetPwStaff();
        pp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rpwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffProtal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffProtal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffProtal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffProtal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffProtal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ckbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton rpw;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
